/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary": "#520070",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#00dbe7",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed-dim": "#4fdbc8",
        "primary-fixed": "#74f5ff",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#3a494b",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "outline": "#849495",
        "secondary-container": "#d05bff",
        "inverse-on-surface": "#313030",
        "surface-tint": "#00dbe7",
        "on-primary-container": "#006a71",
        "secondary": "#ecb1ff",
        "primary": "#e1fdff",
        "tertiary-container": "#68f0dc",
        "secondary-fixed": "#f9d8ff",
        "secondary-fixed-dim": "#ecb1ff",
        "on-primary-fixed-variant": "#004f54",
        "on-tertiary": "#003731",
        "on-tertiary-fixed-variant": "#005048",
        "on-primary-fixed": "#002022",
        "on-secondary-fixed-variant": "#75009e",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "primary-container": "#00f2ff",
        "inverse-primary": "#00696f",
        "on-surface-variant": "#b9cacb",
        "on-primary": "#00363a",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "on-tertiary-container": "#006c61",
        "error": "#ffb4ab",
        "tertiary-fixed": "#71f8e4",
        "on-tertiary-fixed": "#00201c",
        "surface-dim": "#131313",
        "background": "#131313",
        "on-secondary-container": "#480063",
        "surface": "#131313",
        "error-container": "#93000a",
        "on-secondary-fixed": "#320046",
        "tertiary": "#d9fff7",
        casio: {
          bg: '#e8e8e8',
          text: '#222222',
          screen: '#c3cfc8',
          buttonPrimary: '#3b3b3b',
          buttonSecondary: '#e0e0e0',
          buttonAccent: '#e55a5a',
          buttonShift: '#f0c674',
          buttonAlpha: '#cc6666',
        }
      },
      fontFamily: {
        "keypad-secondary": ["Inter", "sans-serif"],
        "display-input": ["JetBrains Mono", "monospace"],
        "display-result": ["Inter", "sans-serif"],
        "keypad-primary": ["Inter", "sans-serif"],
        "label-status": ["JetBrains Mono", "monospace"],
        casio: ['"Courier New"', 'Courier', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      spacing: {
        "keypad-gutter": "8px",
        "display-padding": "32px",
        "container-margin": "16px",
        "section-gap": "24px"
      },
      boxShadow: {
        'glow-primary': '0 0 10px rgba(116, 245, 255, 0.5)',
        'glow-secondary': '0 0 10px rgba(249, 216, 255, 0.5)',
        'inner-glass': 'inset 0 1px 1px rgba(255,255,255,0.1)',
      },
      backgroundImage: {
        'lcd-grid': 'linear-gradient(to right, rgba(0, 0, 0, 0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(0, 0, 0, 0.05) 1px, transparent 1px)',
      }
    },
  },
  plugins: [],
}
